### PR TITLE
Draw circles instead of squares

### PR DESCRIPTION
**Pull request by a7g4**
Also cleaned up some of the shader variable names

### CODE REVIEW

**Comment by a7g4** [comment]
image

**Review by pthien — CHANGES_REQUESTED** [review]
It's a bit unclear what this code is doing, maybe add some comments?

Also why circles instead of squares? Maybe this is the point to start adding marker type as a configurable option

**Comment by a7g4** [comment]
> 
> 
> It's a bit unclear what this code is doing, maybe add some comments?

Will do!

> 
> Also why circles instead of squares? Maybe this is the point to start adding marker type as a configurable option

Yep - there are two things that I want to add to the marker type (for points):
- Size as an enum type so you specify if its pixel size (constant regardless of camera) or world size (so it scales according to camera like it does now)
- Marker type (circle and square are the two easy ones)

The point drawing stuff may need to change because older graphics card don't seem to be able to generate fragments from arbitrarily large "points". In OpenGL you're supposed to check [GL_POINT_SIZE_RANGE](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPointSize.xhtml) to determine the max size, but I didn't see an equivalent in WebGPU so maybe it doesn't have a max size?

**Comment by a7g4** [comment]
Oh - why circles vs squares now?

Squares that rotate to face you are creepy :P Circles that rotate to face you are just spheres :)

**Review by pthien — APPROVED** [review]

**Pull request merged**
